apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: front-end
  namespace: sock-shop
spec:
  template:
    metadata:
      name: front-end-v1
      labels:
        version: v1
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "200"
    spec:
      containers:
      - image: registry.hub.docker.com/kewnt/sock-shop:frontend
        ports:
        - containerPort: 8079
        env:
        - name: SESSION_REDIS
          value: "true"
        command: [ "/usr/local/bin/npm" ]
        args: [ "start", "--", "--domain=sock-shop.svc.cluster.local" ]
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        livenessProbe:
          httpGet:
            path: /
        readinessProbe:
          httpGet:
            path: /
#  traffic:
#    - tag: v2
#      revisionName: front-end-v2
#      percent: 25
#    - tag: v1
#      revisionName: front-end-v1
#      percent: 75