apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: user
  namespace: sock-shop
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "200"
      labels:
        version: v1
    spec:
      containers:
      - image: registry.hub.docker.com/weaveworksdemos/user:0.4.7
        ports:
        - containerPort: 80
        env:
        - name: mongo
          value: "user-db:27017"
        resources:
          limits:
            cpu: 300m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
