apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: catalogue
  namespace: sock-shop
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "200"
      labels:
        version: v1
    spec:
      containers:
      - image: registry.hub.docker.com/weaveworksdemos/catalogue:0.3.5
        command: ["/app"]
        args:
        - "-port=80"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 100Mi
