apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payment
  namespace: sock-shop
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "200"
    spec:
      containers:
      - image: weaveworksdemos/payment:0.4.3
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
